# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SSRFun_cpp <- function(d_mat, delta_mat) {
    .Call(`_GBMDSpackage_SSRFun_cpp`, d_mat, delta_mat)
}

SSRFun_cpp <- function(d_mat, delta_mat) {
    .Call(`_GBMDSpackage_SSRFun_cpp`, d_mat, delta_mat)
}

bisectionFun_cpp <- function(low, high, W, logL, phi) {
    .Call(`_GBMDSpackage_bisectionFun_cpp`, low, high, W, logL, phi)
}

bisectionFun_cpp <- function(low, high, W, logL, phi) {
    .Call(`_GBMDSpackage_bisectionFun_cpp`, low, high, W, logL, phi)
}

dinvgamma_cpp <- function(x, shape, rate, log) {
    .Call(`_GBMDSpackage_dinvgamma_cpp`, x, shape, rate, log)
}

dinvgamma_cpp <- function(x, shape, rate, log) {
    .Call(`_GBMDSpackage_dinvgamma_cpp`, x, shape, rate, log)
}

distRcpp <- function(X, metric) {
    .Call(`_GBMDSpackage_distRcpp`, X, metric)
}

dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_GBMDSpackage_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_GBMDSpackage_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

dproposalFun_cpp <- function(dist_mat, para_result_l, para_result_r, metric, hyperparList) {
    .Call(`_GBMDSpackage_dproposalFun_cpp`, dist_mat, para_result_l, para_result_r, metric, hyperparList)
}

dproposalFun_cpp <- function(dist_mat, para_result_l, para_result_r, metric, hyperparList) {
    .Call(`_GBMDSpackage_dproposalFun_cpp`, dist_mat, para_result_l, para_result_r, metric, hyperparList)
}

initialFun_SN_cpp <- function(cmds_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_SN_cpp`, cmds_result, dist_mat, metric, hyperparList)
}

initialFun_SN_cpp <- function(cmds_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_SN_cpp`, cmds_result, dist_mat, metric, hyperparList)
}

initialFun_SN_incr_cpp <- function(prev_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_SN_incr_cpp`, prev_result, dist_mat, metric, hyperparList)
}

initialFun_SN_incr_cpp <- function(prev_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_SN_incr_cpp`, prev_result, dist_mat, metric, hyperparList)
}

initialFun_T_cpp <- function(cmds_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_T_cpp`, cmds_result, dist_mat, metric, hyperparList)
}

initialFun_T_cpp <- function(cmds_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_T_cpp`, cmds_result, dist_mat, metric, hyperparList)
}

initialFun_T_incr_cpp <- function(prev_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_T_incr_cpp`, prev_result, dist_mat, metric, hyperparList)
}

initialFun_T_incr_cpp <- function(prev_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_T_incr_cpp`, prev_result, dist_mat, metric, hyperparList)
}

initialFun_cpp <- function(cmds_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_cpp`, cmds_result, dist_mat, metric, hyperparList)
}

initialFun_cpp <- function(cmds_result, dist_mat, metric, hyperparList) {
    .Call(`_GBMDSpackage_initialFun_cpp`, cmds_result, dist_mat, metric, hyperparList)
}

likelihoodFun_SN_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList) {
    .Call(`_GBMDSpackage_likelihoodFun_SN_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList)
}

likelihoodFun_SN_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList) {
    .Call(`_GBMDSpackage_likelihoodFun_SN_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList)
}

likelihoodFun_SN_incr_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr) {
    .Call(`_GBMDSpackage_likelihoodFun_SN_incr_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr)
}

likelihoodFun_SN_incr_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr) {
    .Call(`_GBMDSpackage_likelihoodFun_SN_incr_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr)
}

likelihoodFun_T_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList) {
    .Call(`_GBMDSpackage_likelihoodFun_T_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList)
}

likelihoodFun_T_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList) {
    .Call(`_GBMDSpackage_likelihoodFun_T_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList)
}

likelihoodFun_T_incr_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr) {
    .Call(`_GBMDSpackage_likelihoodFun_T_incr_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr)
}

likelihoodFun_T_incr_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr) {
    .Call(`_GBMDSpackage_likelihoodFun_T_incr_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList, n_incr)
}

likelihoodFun_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList) {
    .Call(`_GBMDSpackage_likelihoodFun_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList)
}

likelihoodFun_cpp <- function(dist_mat, upper_bound, proposal_result, metric, hyperparList) {
    .Call(`_GBMDSpackage_likelihoodFun_cpp`, dist_mat, upper_bound, proposal_result, metric, hyperparList)
}

logReferenceRatio_cpp <- function(new_x, current_x, prev_x) {
    .Call(`_GBMDSpackage_logReferenceRatio_cpp`, new_x, current_x, prev_x)
}

logReferenceRatio_cpp <- function(new_x, current_x, prev_x) {
    .Call(`_GBMDSpackage_logReferenceRatio_cpp`, new_x, current_x, prev_x)
}

multinomialResampleFun_cpp <- function(W) {
    .Call(`_GBMDSpackage_multinomialResampleFun_cpp`, W)
}

multinomialResampleFun_cpp <- function(W) {
    .Call(`_GBMDSpackage_multinomialResampleFun_cpp`, W)
}

rmvnorm_arma_stochvol <- function(n, precision, location) {
    .Call(`_GBMDSpackage_rmvnorm_arma_stochvol`, n, precision, location)
}

rmvnorm_arma_stochvol <- function(n, precision, location) {
    .Call(`_GBMDSpackage_rmvnorm_arma_stochvol`, n, precision, location)
}

mypsnorm_cpp <- function(q, mean, sd, psi) {
    .Call(`_GBMDSpackage_mypsnorm_cpp`, q, mean, sd, psi)
}

mypsnorm_cpp <- function(q, mean, sd, psi) {
    .Call(`_GBMDSpackage_mypsnorm_cpp`, q, mean, sd, psi)
}

proposalFun_SN_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_SN_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x)
}

proposalFun_SN_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_SN_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x)
}

proposalFun_SN_incr_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_SN_incr_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x)
}

proposalFun_SN_incr_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_SN_incr_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x)
}

proposalFun_T_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_T_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x)
}

proposalFun_T_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_T_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x)
}

proposalFun_T_incr_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_T_incr_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x)
}

proposalFun_T_incr_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_T_incr_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, n_incr, upper_bound, update_list, update_list_x)
}

proposalFun_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x)
}

proposalFun_cpp <- function(dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x) {
    .Call(`_GBMDSpackage_proposalFun_cpp`, dist_mat, currentVal, prevX, annealingPar, metric, hyperparList, upper_bound, update_list, update_list_x)
}

psnorm_cpp <- function(q, mean, sd, psi) {
    .Call(`_GBMDSpackage_psnorm_cpp`, q, mean, sd, psi)
}

psnorm_cpp <- function(q, mean, sd, psi) {
    .Call(`_GBMDSpackage_psnorm_cpp`, q, mean, sd, psi)
}

rCESSFun_cpp <- function(W, logL, num, phi) {
    .Call(`_GBMDSpackage_rCESSFun_cpp`, W, logL, num, phi)
}

rCESSFun_cpp <- function(W, logL, num, phi) {
    .Call(`_GBMDSpackage_rCESSFun_cpp`, W, logL, num, phi)
}

rESSFun_cpp <- function(logW) {
    .Call(`_GBMDSpackage_rESSFun_cpp`, logW)
}

rESSFun_cpp <- function(logW) {
    .Call(`_GBMDSpackage_rESSFun_cpp`, logW)
}

reference_d_x_cpp <- function(x, prev_x) {
    .Call(`_GBMDSpackage_reference_d_x_cpp`, x, prev_x)
}

reference_d_x_cpp <- function(x, prev_x) {
    .Call(`_GBMDSpackage_reference_d_x_cpp`, x, prev_x)
}

reference_d_x_cpp <- function(x, prev_x) {
    .Call(`_GBMDSpackage_reference_d_x_cpp`, x, prev_x)
}

rmvnorm_arma <- function(n, mu, sigma) {
    .Call(`_GBMDSpackage_rmvnorm_arma`, n, mu, sigma)
}

rmvnorm_arma <- function(n, mu, sigma) {
    .Call(`_GBMDSpackage_rmvnorm_arma`, n, mu, sigma)
}

stressFun_cpp <- function(d_mat, delta_mat) {
    .Call(`_GBMDSpackage_stressFun_cpp`, d_mat, delta_mat)
}

stressFun_cpp <- function(d_mat, delta_mat) {
    .Call(`_GBMDSpackage_stressFun_cpp`, d_mat, delta_mat)
}

